// Shared location constants for property creation and filtering
// Ensures consistency across the application

export const PROPERTY_TYPES = ['House', 'Loft', 'Apartment', 'Studio', 'Castle', 'Cabin', 'Condo', 'Villa', 'Bungalow', 'Townhouse'] as const;

export type PropertyType = typeof PROPERTY_TYPES[number];

// Hardcoded countries list for better performance (no need to load world-countries library)
export interface Country {
  cca2: string;
  name: { common: string };
}

export const COUNTRIES_LIST: Country[] = [
  { cca2: 'AF', name: { common: 'Afghanistan' } },
  { cca2: 'AL', name: { common: 'Albania' } },
  { cca2: 'DZ', name: { common: 'Algeria' } },
  { cca2: 'AO', name: { common: 'Angola' } },
  { cca2: 'AR', name: { common: 'Argentina' } },
  { cca2: 'AM', name: { common: 'Armenia' } },
  { cca2: 'AU', name: { common: 'Australia' } },
  { cca2: 'AT', name: { common: 'Austria' } },
  { cca2: 'AZ', name: { common: 'Azerbaijan' } },
  { cca2: 'BS', name: { common: 'Bahamas' } },
  { cca2: 'BH', name: { common: 'Bahrain' } },
  { cca2: 'BD', name: { common: 'Bangladesh' } },
  { cca2: 'BB', name: { common: 'Barbados' } },
  { cca2: 'BY', name: { common: 'Belarus' } },
  { cca2: 'BE', name: { common: 'Belgium' } },
  { cca2: 'BZ', name: { common: 'Belize' } },
  { cca2: 'BF', name: { common: 'Burkina Faso' } },
  { cca2: 'BI', name: { common: 'Burundi' } },
  { cca2: 'BT', name: { common: 'Bhutan' } },
  { cca2: 'BO', name: { common: 'Bolivia' } },
  { cca2: 'BA', name: { common: 'Bosnia and Herzegovina' } },
  { cca2: 'BW', name: { common: 'Botswana' } },
  { cca2: 'BR', name: { common: 'Brazil' } },
  { cca2: 'BG', name: { common: 'Bulgaria' } },
  { cca2: 'CA', name: { common: 'Canada' } },
  { cca2: 'CM', name: { common: 'Cameroon' } },
  { cca2: 'CL', name: { common: 'Chile' } },
  { cca2: 'CN', name: { common: 'China' } },
  { cca2: 'CO', name: { common: 'Colombia' } },
  { cca2: 'CG', name: { common: 'Republic of the Congo' } },
  { cca2: 'CD', name: { common: 'Democratic Republic of the Congo' } },
  { cca2: 'CR', name: { common: 'Costa Rica' } },
  { cca2: 'HR', name: { common: 'Croatia' } },
  { cca2: 'CU', name: { common: 'Cuba' } },
  { cca2: 'CY', name: { common: 'Cyprus' } },
  { cca2: 'CZ', name: { common: 'Czech Republic' } },
  { cca2: 'DK', name: { common: 'Denmark' } },
  { cca2: 'DO', name: { common: 'Dominican Republic' } },
  { cca2: 'CD', name: { common: 'Democratic Republic of the Congo' } },
  { cca2: 'EC', name: { common: 'Ecuador' } },
  { cca2: 'EG', name: { common: 'Egypt' } },
  { cca2: 'SV', name: { common: 'El Salvador' } },
  { cca2: 'EE', name: { common: 'Estonia' } },
  { cca2: 'ET', name: { common: 'Ethiopia' } },
  { cca2: 'SZ', name: { common: 'Eswatini' } },
  { cca2: 'GQ', name: { common: 'Equatorial Guinea' } },
  { cca2: 'FI', name: { common: 'Finland' } },
  { cca2: 'FR', name: { common: 'France' } },
  { cca2: 'GF', name: { common: 'French Guiana' } },
  { cca2: 'GA', name: { common: 'Gabon' } },
  { cca2: 'GE', name: { common: 'Georgia' } },
  { cca2: 'DE', name: { common: 'Germany' } },
  { cca2: 'GH', name: { common: 'Ghana' } },
  { cca2: 'GR', name: { common: 'Greece' } },
  { cca2: 'GY', name: { common: 'Guyana' } },
  { cca2: 'HT', name: { common: 'Haiti' } },
  { cca2: 'HN', name: { common: 'Honduras' } },
  { cca2: 'HU', name: { common: 'Hungary' } },
  { cca2: 'IS', name: { common: 'Iceland' } },
  { cca2: 'IN', name: { common: 'India' } },
  { cca2: 'ID', name: { common: 'Indonesia' } },
  { cca2: 'IR', name: { common: 'Iran' } },
  { cca2: 'IQ', name: { common: 'Iraq' } },
  { cca2: 'IE', name: { common: 'Ireland' } },
  { cca2: 'IL', name: { common: 'Israel' } },
  { cca2: 'IT', name: { common: 'Italy' } },
  { cca2: 'CI', name: { common: 'Côte d\'Ivoire' } },
  { cca2: 'JM', name: { common: 'Jamaica' } },
  { cca2: 'JP', name: { common: 'Japan' } },
  { cca2: 'JO', name: { common: 'Jordan' } },
  { cca2: 'KZ', name: { common: 'Kazakhstan' } },
  { cca2: 'KE', name: { common: 'Kenya' } },
  { cca2: 'KH', name: { common: 'Cambodia' } },
  { cca2: 'KG', name: { common: 'Kyrgyzstan' } },
  { cca2: 'KW', name: { common: 'Kuwait' } },
  { cca2: 'LA', name: { common: 'Laos' } },
  { cca2: 'LV', name: { common: 'Latvia' } },
  { cca2: 'LB', name: { common: 'Lebanon' } },
  { cca2: 'LS', name: { common: 'Lesotho' } },
  { cca2: 'LT', name: { common: 'Lithuania' } },
  { cca2: 'LU', name: { common: 'Luxembourg' } },
  { cca2: 'MG', name: { common: 'Madagascar' } },
  { cca2: 'MW', name: { common: 'Malawi' } },
  { cca2: 'MY', name: { common: 'Malaysia' } },
  { cca2: 'ML', name: { common: 'Mali' } },
  { cca2: 'MT', name: { common: 'Malta' } },
  { cca2: 'MA', name: { common: 'Morocco' } },
  { cca2: 'MX', name: { common: 'Mexico' } },
  { cca2: 'MD', name: { common: 'Moldova' } },
  { cca2: 'MM', name: { common: 'Myanmar' } },
  { cca2: 'MZ', name: { common: 'Mozambique' } },
  { cca2: 'ME', name: { common: 'Montenegro' } },
  { cca2: 'NP', name: { common: 'Nepal' } },
  { cca2: 'NL', name: { common: 'Netherlands' } },
  { cca2: 'NZ', name: { common: 'New Zealand' } },
  { cca2: 'NI', name: { common: 'Nicaragua' } },
  { cca2: 'NG', name: { common: 'Nigeria' } },
  { cca2: 'NO', name: { common: 'Norway' } },
  { cca2: 'NE', name: { common: 'Niger' } },
  { cca2: 'NA', name: { common: 'Namibia' } },
  { cca2: 'MK', name: { common: 'North Macedonia' } },
  { cca2: 'OM', name: { common: 'Oman' } },
  { cca2: 'PA', name: { common: 'Panama' } },
  { cca2: 'PK', name: { common: 'Pakistan' } },
  { cca2: 'PY', name: { common: 'Paraguay' } },
  { cca2: 'PE', name: { common: 'Peru' } },
  { cca2: 'PH', name: { common: 'Philippines' } },
  { cca2: 'PL', name: { common: 'Poland' } },
  { cca2: 'PT', name: { common: 'Portugal' } },
  { cca2: 'PS', name: { common: 'Palestine' } },
  { cca2: 'QA', name: { common: 'Qatar' } },
  { cca2: 'RO', name: { common: 'Romania' } },
  { cca2: 'RS', name: { common: 'Serbia' } },
  { cca2: 'RW', name: { common: 'Rwanda' } },
  { cca2: 'SN', name: { common: 'Senegal' } },
  { cca2: 'SK', name: { common: 'Slovakia' } },
  { cca2: 'SI', name: { common: 'Slovenia' } },
  { cca2: 'SG', name: { common: 'Singapore' } },
  { cca2: 'ZA', name: { common: 'South Africa' } },
  { cca2: 'KR', name: { common: 'South Korea' } },
  { cca2: 'SS', name: { common: 'South Sudan' } },
  { cca2: 'ES', name: { common: 'Spain' } },
  { cca2: 'SR', name: { common: 'Suriname' } },
  { cca2: 'SE', name: { common: 'Sweden' } },
  { cca2: 'CH', name: { common: 'Switzerland' } },
  { cca2: 'SY', name: { common: 'Syria' } },
  { cca2: 'TW', name: { common: 'Taiwan' } },
  { cca2: 'TJ', name: { common: 'Tajikistan' } },
  { cca2: 'TZ', name: { common: 'Tanzania' } },
  { cca2: 'TH', name: { common: 'Thailand' } },
  { cca2: 'TG', name: { common: 'Togo' } },
  { cca2: 'TT', name: { common: 'Trinidad and Tobago' } },
  { cca2: 'TN', name: { common: 'Tunisia' } },
  { cca2: 'TR', name: { common: 'Turkey' } },
  { cca2: 'TM', name: { common: 'Turkmenistan' } },
  { cca2: 'UG', name: { common: 'Uganda' } },
  { cca2: 'UA', name: { common: 'Ukraine' } },
  { cca2: 'AE', name: { common: 'United Arab Emirates' } },
  { cca2: 'GB', name: { common: 'United Kingdom' } },
  { cca2: 'US', name: { common: 'United States' } },
  { cca2: 'UY', name: { common: 'Uruguay' } },
  { cca2: 'UZ', name: { common: 'Uzbekistan' } },
  { cca2: 'VE', name: { common: 'Venezuela' } },
  { cca2: 'VN', name: { common: 'Vietnam' } },
  { cca2: 'YE', name: { common: 'Yemen' } },
  { cca2: 'ZM', name: { common: 'Zambia' } },
  { cca2: 'ZW', name: { common: 'Zimbabwe' } },
  { cca2: 'TD', name: { common: 'Chad' } },
  { cca2: 'SD', name: { common: 'Sudan' } },
];

export const COUNTRIES_AND_CITIES: { [key: string]: string[] } = {
  'US': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
  'CA': ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener'],
  'GB': ['London', 'Manchester', 'Birmingham', 'Liverpool', 'Leeds', 'Glasgow', 'Edinburgh', 'Bristol', 'Cardiff', 'Belfast'],
  'AU': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Central Coast', 'Wollongong'],
  'DE': ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'],
  'FR': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
  'IT': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania'],
  'ES': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao'],
  'JP': ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kawasaki', 'Saitama', 'Hiroshima'],
  'CN': ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Tianjin', 'Wuhan', 'Dongguan', 'Chengdu', 'Nanjing', 'Hangzhou'],
  'IN': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Surat', 'Pune', 'Jaipur'],
  'BR': ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre'],
  'MX': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Juárez', 'Torreón', 'Querétaro', 'Mérida'],
  'NL': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen', 'Almere', 'Breda', 'Nijmegen'],
  'SE': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Linköping', 'Örebro', 'Västerås', 'Helsingborg', 'Jönköping', 'Norrköping'],
  'CH': ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Winterthur', 'Lucerne', 'St. Gallen', 'Lugano', 'Biel/Bienne'],
  'SG': ['Singapore'],
  'AE': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain'],
  'ZA': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Pietermaritzburg', 'Benoni', 'Tembisa'],
  'NZ': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin', 'Lower Hutt', 'Palmerston North', 'Napier', 'Rotorua'],
  'MA': ['Casablanca', 'Rabat', 'Fès', 'Marrakech', 'Meknès', 'Oujda', 'Kenitra', 'Agadir', 'Tétouan', 'Safi'],
  'EG': ['Cairo', 'Alexandria', 'Giza', 'Shubra El-Kheima', 'Port Said', 'Suez', 'Luxor', 'Mansoura', 'Tanta', 'Asyut'],
  'SA': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Sulṭānah', 'Dammam', 'Ta\'if', 'Tabuk', 'Buraydah', 'Khamis Mushait'],
  'TR': ['Istanbul', 'Ankara', 'İzmir', 'Bursa', 'Adana', 'Gaziantep', 'Konya', 'Antalya', 'Kayseri', 'Mersin'],
  'TH': ['Bangkok', 'Nonthaburi', 'Nakhon Ratchasima', 'Chiang Mai', 'Hat Yai', 'Pak Kret', 'Si Racha', 'Phra Pradaeng', 'Lampang', 'Khon Kaen'],
  'KR': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Goyang', 'Seongnam', 'Ulsan'],
  'MY': ['Kuala Lumpur', 'Seberang Perai', 'Johor Bahru', 'Ipoh', 'Kuching', 'Kota Kinabalu', 'Shah Alam', 'Klang', 'Petaling Jaya', 'Sandakan'],
  'ID': ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang', 'Tangerang', 'South Tangerang', 'Batam'],
  'PH': ['Quezon City', 'Manila', 'Caloocan', 'Davao City', 'Cebu City', 'Zamboanga City', 'Taguig', 'Antipolo', 'Pasig', 'Cagayan de Oro'],
  'VN': ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Haiphong', 'Biên Hòa', 'Cần Thơ', 'Huế', 'Nha Trang', 'Cam Ranh', 'Vũng Tàu'],
  'PK': ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 'Peshawar', 'Multan', 'Hyderabad', 'Islamabad', 'Quetta'],
  'BD': ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Comilla', 'Barisal', 'Sylhet', 'Narayanganj', 'Rangpur', 'Mymensingh'],
  'NG': ['Lagos', 'Kano', 'Ibadan', 'Kaduna', 'Port Harcourt', 'Benin City', 'Maiduguri', 'Zaria', 'Aba', 'Jos'],
  'KE': ['Nairobi', 'Mombasa', 'Nakuru', 'Eldoret', 'Kisumu', 'Thika', 'Malindi', 'Kitale', 'Garissa', 'Kakamega'],
  'GH': ['Accra', 'Kumasi', 'Tamale', 'Takoradi', 'Atsiaman', 'Tema', 'Cape Coast', 'Obuasi', 'Abengourou', 'Divo'],
  'TN': ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan', 'Bizerte', 'Gabès', 'Ariana', 'Gafsa', 'El Mourouj'],
  'DZ': ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Djelfa', 'Sétif', 'Sidi Bel Abbès', 'Biskra'],
  'JO': ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Al-Quwaysimah', 'Wadi Al-Seer', 'Tafilah', 'Aqaba', 'Madaba', 'As-Salt'],
  'LB': ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Nabatieh', 'Jounieh', 'Zahle', 'Baalbek', 'Byblos', 'Batroun'],
  'IL': ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod', 'Netanya', 'Beer Sheva', 'Holon', 'Bnei Brak'],
  'QA': ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Dukhan', 'Mesaieed', 'Al Shamal', 'Al Daayen', 'Al Shahaniya'],
  'KW': ['Kuwait City', 'Al Ahmadi', 'Hawalli', 'Al Farwaniyah', 'Al Jahra', 'Mubarak Al-Kabeer', 'Al Asimah', 'Salmiya', 'Sabah Al-Salem', 'Al Fintas'],
  'OM': ['Muscat', 'Seeb', 'Salalah', 'Bawshar', 'Sohar', 'As Suwayq', 'Ibri', 'Saham', 'Barka', 'Rustaq'],
  'BH': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'A\'ali', 'Isa Town', 'Sitra', 'Budaiya', 'Jidhafs', 'Al Hadd'],
  'CY': ['Nicosia', 'Limassol', 'Larnaca', 'Famagusta', 'Paphos', 'Kyrenia', 'Protaras', 'Paralimni', 'Morphou', 'Aradippou'],
  'MT': ['Birkirkara', 'Qormi', 'Mosta', 'Żabbar', 'San Pawl il-Baħar', 'Fgura', 'Żejtun', 'Sliema', 'Marsa', 'San Ġwann'],
  'IS': ['Reykjavík', 'Kópavogur', 'Hafnarfjörður', 'Akureyri', 'Reykjanesbær', 'Garðabær', 'Mosfellsbær', 'Árborg', 'Akranes', 'Fjardabyggd'],
  'NO': ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen', 'Fredrikstad', 'Kristiansand', 'Sandnes', 'Tromsø', 'Sarpsborg'],
  'DK': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Frederiksberg', 'Esbjerg', 'Randers', 'Kolding', 'Vejle', 'Roskilde'],
  'FI': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio', 'Kouvola'],
  'PT': ['Lisbon', 'Porto', 'Amadora', 'Braga', 'Setúbal', 'Coimbra', 'Queluz', 'Funchal', 'Cacém', 'Vila Nova de Gaia'],
  'GR': ['Athens', 'Thessaloniki', 'Patras', 'Piraeus', 'Larissa', 'Heraklion', 'Peristeri', 'Kallithea', 'Acharnes', 'Kalamaria'],
  'HU': ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs', 'Győr', 'Nyíregyháza', 'Kecskemét', 'Székesfehérvár', 'Szombathely'],
  'CZ': ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc', 'Ústí nad Labem', 'České Budějovice', 'Hradec Králové', 'Pardubice'],
  'PL': ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice'],
  'RO': ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov', 'Galați', 'Ploiești', 'Oradea'],
  'SK': ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Banská Bystrica', 'Nitra', 'Trnava', 'Martin', 'Trenčín', 'Poprad'],
  'SI': ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Velenje', 'Koper', 'Novo Mesto', 'Ptuj', 'Kamnik', 'Jesenice'],
  'HR': ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Pula', 'Slavonski Brod', 'Karlovac', 'Varaždin', 'Šibenik'],
  'BA': ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar', 'Bihać', 'Bugojno', 'Brčko', 'Bijeljina', 'Prijedor'],
  'ME': ['Podgorica', 'Nikšić', 'Herceg Novi', 'Pljevlja', 'Budva', 'Bar', 'Berane', 'Ulcinj', 'Bijelo Polje', 'Cetinje'],
  'MK': ['Skopje', 'Bitola', 'Kumanovo', 'Prilep', 'Tetovo', 'Veles', 'Štip', 'Ohrid', 'Gostivar', 'Strumica'],
  'AL': ['Tirana', 'Durrës', 'Vlorë', 'Elbasan', 'Shkodër', 'Korçë', 'Fier', 'Berat', 'Lushnjë', 'Pogradec'],
  'RS': ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica', 'Zrenjanin', 'Pančevo', 'Čačak', 'Novi Pazar', 'Kraljevo'],
  'BG': ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora', 'Pleven', 'Sliven', 'Dobrich', 'Shumen'],
  'EE': ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve', 'Viljandi', 'Rakvere', 'Maardu', 'Kuressaare', 'Sillamäe'],
  'LV': ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala', 'Ventspils', 'Rēzekne', 'Valmiera', 'Ogre', 'Tukums'],
  'LT': ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys', 'Alytus', 'Marijampolė', 'Mažeikiai', 'Jonava', 'Utena'],
  'LU': ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck', 'Bettembourg', 'Wiltz', 'Rumelange', 'Grevenmacher', 'Echternach'],
  'IE': ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda', 'Dundalk', 'Bray', 'Swords', 'Navan'],
  'AT': ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'Sankt Pölten', 'Dornbirn'],
  'BE': ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Leuven', 'Mons', 'Aalst'],
  'UA': ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv', 'Kryvyi Rih', 'Mykolaiv', 'Mariupol'],
  'BY': ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Hrodna', 'Brest', 'Babruysk', 'Baranovichi', 'Pinsk', 'Orsha'],
  'MD': ['Chișinău', 'Tiraspol', 'Bălți', 'Bendery', 'Rîbnița', 'Cahul', 'Ungheni', 'Soroca', 'Orhei', 'Dubăsari'],
  'GE': ['Tbilisi', 'Kutaisi', 'Batumi', 'Sukhumi', 'Rustavi', 'Zugdidi', 'Gori', 'Poti', 'Samtredia', 'Khashuri'],
  'AM': ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Hrazdan', 'Abovyan', 'Kapan', 'Ararat', 'Armavir', 'Gavarr'],
  'AZ': ['Baku', 'Ganja', 'Sumqayıt', 'Mingachevir', 'Lankaran', 'Shirvan', 'Nakhchivan', 'Shaki', 'Yevlakh', 'Khirdalan'],
  'KZ': ['Almaty', 'Nur-Sultan', 'Shymkent', 'Aktobe', 'Karaganda', 'Taraz', 'Pavlodar', 'Ust-Kamenogorsk', 'Kyzylorda', 'Semey'],
  'UZ': ['Tashkent', 'Namangan', 'Samarkand', 'Andijan', 'Bukhara', 'Nukus', 'Qarshi', 'Kokand', 'Chirchiq', 'Fergana'],
  'TM': ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary', 'Balkanabat', 'Bayramaly', 'Türkmenbaşy', 'Tejen', 'Abadan', 'Yolöten'],
  'TJ': ['Dushanbe', 'Khujand', 'Kulob', 'Qurghonteppa', 'Istaravshan', 'Konibodom', 'Tursunzoda', 'Isfara', 'Panjakent', 'Shakhrisabz'],
  'KG': ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol', 'Tokmok', 'Uzgen', 'Balykchy', 'Kara-Balta', 'Naryn', 'Talas'],
  'MN': ['Ulaanbaatar', 'Erdenet', 'Darhan', 'Khovd', 'Ölgii', 'Ulaangom', 'Kharkhorin', 'Mandalgovi', 'Choir', 'Sainshand'],
  'NP': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Birgunj', 'Dharan', 'Bharatpur', 'Janakpur', 'Hetauda', 'Itahari'],
  'LK': ['Colombo', 'Gampaha', 'Kalmunai', 'Jaffna', 'Kandy', 'Trincomalee', 'Batticaloa', 'Anuradhapura', 'Vavuniya', 'Matale'],
  'MM': ['Yangon', 'Mandalay', 'Naypyidaw', 'Mawlamyine', 'Bago', 'Pathein', 'Monywa', 'Sittwe', 'Meiktila', 'Myingyan'],
  'KH': ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sisophon', 'Poipet', 'Kampong Cham', 'Pursat', 'Kampong Chhnang', 'Koh Kong', 'Kratie'],
  'LA': ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang', 'Xam Nua', 'Thakhek', 'Muang Xay', 'Vang Vieng', 'Pakxan', 'Phonsavan'],
  'BT': ['Thimphu', 'Phuntsholing', 'Paro', 'Punakha', 'Wangdue Phodrang', 'Jakar', 'Samdrup Jongkhar', 'Trashigang', 'Mongar', 'Trongsa'],
  'AF': ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad', 'Lashkargah', 'Taloqan', 'Puli Khumri', 'Ghazni', 'Sheberghan'],
  'IR': ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz', 'Ahvaz', 'Qom', 'Kermanshah', 'Urmia'],
  'IQ': ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Najaf', 'Karbala', 'Kirkuk', 'Sulaymaniyah', 'Nasiriyah', 'Amarah'],
  'SY': ['Damascus', 'Aleppo', 'Homs', 'Hama', 'Latakia', 'Deir ez-Zor', 'Raqqa', 'Idlib', 'Douma', 'Al-Hasakah'],
  'YE': ['Sana\'a', 'Aden', 'Taiz', 'Al Hudaydah', 'Mukalla', 'Ibb', 'Dhamar', 'Amran', 'Sayyan', 'Zabid'],
  'PS': ['Gaza', 'Hebron', 'Nablus', 'Rafah', 'Khan Yunis', 'Jabalia', 'Hebron', 'Bethlehem', 'Beit Lahia', 'Beit Hanoun'],
  'ET': ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Nazret', 'Bahir Dar', 'Gondar', 'Dessie', 'Jimma', 'Jijiga', 'Shashamane'],
  'TZ': ['Dar es Salaam', 'Dodoma', 'Mwanza', 'Zanzibar City', 'Arusha', 'Mbeya', 'Morogoro', 'Tanga', 'Kahama', 'Tabora'],
  'UG': ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja', 'Bwizibwera', 'Mbale', 'Mukono', 'Kasese', 'Masaka'],
  'ZW': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru', 'Epworth', 'Kwekwe', 'Kadoma', 'Masvingo', 'Chinhoyi'],
  'ZM': ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola', 'Mufulira', 'Luanshya', 'Livingstone', 'Kasama', 'Chipata'],
  'MZ': ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio', 'Tete', 'Quelimane', 'Mocuba', 'Lichinga', 'Pemba'],
  'MG': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga', 'Toliara', 'Antsiranana', 'Antanifotsy', 'Ambovombe', 'Alajafaravola'],
  'AO': ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Kuito', 'Lubango', 'Malanje', 'Namibe', 'Soyo', 'Cabinda'],
  'CM': ['Yaoundé', 'Douala', 'Garoua', 'Kousséri', 'Bamenda', 'Maroua', 'Bafoussam', 'Mokolo', 'Ngaoundéré', 'Bertoua'],
  'CI': ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro', 'San-Pédro', 'Korhogo', 'Man', 'Gagnoa', 'Abengourou', 'Divo'],
  'SN': ['Dakar', 'Pikine', 'Touba', 'Thiès', 'Kaolack', 'Ziguinchor', 'Saint-Louis', 'Diourbel', 'Louga', 'Tambacounda'],
  'ML': ['Bamako', 'Sikasso', 'Mopti', 'Koutiala', 'Ségou', 'Kayes', 'Markala', 'Kolokani', 'Kati', 'Gao'],
  'BF': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya', 'Banfora', 'Pouytenga', 'Kaya', 'Tenkodogo', 'Réo', 'Houndé'],
  'NE': ['Niamey', 'Zinder', 'Maradi', 'Agadez', 'Alaghsas', 'Tahoua', 'Dosso', 'Birni N Konni', 'Tessaoua', 'Gaya'],
  'TD': ['N\'Djamena', 'Moundou', 'Sarh', 'Abéché', 'Kelo', 'Koumra', 'Pala', 'Am Timan', 'Bongor', 'Mongo'],
  'SD': ['Khartoum', 'Omdurman', 'Nyala', 'Port Sudan', 'Kassala', 'El Obeid', 'Kosti', 'Wad Madani', 'El Fasher', 'Dongola'],
  'SS': ['Juba', 'Winejok', 'Malakal', 'Wau', 'Pajok', 'Yei', 'Nimule', 'Bentiu', 'Bor', 'Rumbek'],
  'RW': ['Kigali', 'Butare', 'Gitarama', 'Musanze', 'Kibuye', 'Cyangugu', 'Kibungo', 'Rwamagana', 'Nyanza', 'Muhanga'],
  'BI': ['Bujumbura', 'Muyinga', 'Ruyigi', 'Gitega', 'Ngozi', 'Rutana', 'Bururi', 'Makamba', 'Kayanza', 'Muramvya'],
  'CG': ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Loandjili', 'Madingou', 'Sibiti', 'Impfondo', 'Ouésso', 'Mossendjo'],
  'CD': ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani', 'Bukavu', 'Tshikapa', 'Kolwezi', 'Likasi', 'Goma'],
  'GA': ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda', 'Mouila', 'Lambaréné', 'Tchibanga', 'Koulamoutou', 'Makokou'],
  'GQ': ['Malabo', 'Bata', 'Ebebiyin', 'Aconibe', 'Evinayong', 'Mongomo', 'Rebola', 'Mikomeseng', 'Bidjabidjan', 'Niefang'],
  'BW': ['Gaborone', 'Francistown', 'Molepolole', 'Selebi-Phikwe', 'Maun', 'Serowe', 'Kanye', 'Mahalapye', 'Mogoditshane', 'Mochudi'],
  'NA': ['Windhoek', 'Rundu', 'Walvis Bay', 'Oshakati', 'Swakopmund', 'Katima Mulilo', 'Otjiwarongo', 'Okahandja', 'Ondangwa', 'Tsumeb'],
  'SZ': ['Mbabane', 'Manzini', 'Lobamba', 'Siteki', 'Piggs Peak', 'Malkerns', 'Nhlangano', 'Mhlume', 'Big Bend', 'Simunye'],
  'LS': ['Maseru', 'Teyateyaneng', 'Mafeteng', 'Hlotse', 'Mohale\'s Hoek', 'Maputsoe', 'Qacha\'s Nek', 'Butha-Buthe', 'Leribe', ' Mokhotlong'],
  'MW': ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba', 'Karonga', 'Kasungu', 'Mangochi', 'Salima', 'Nkhotakota', 'Liwonde'],
  'CU': ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Guantánamo', 'Santa Clara', 'Diez de Octubre', 'Matanzas', 'Cienfuegos', 'Pinar del Río'],
  'HT': ['Port-au-Prince', 'Carrefour', 'Delmas', 'Pétion-Ville', 'Port-de-Paix', 'Jacmel', 'Leogâne', 'Les Cayes', 'Jerémie', 'Cap-Haïtien'],
  'DO': ['Santo Domingo', 'Santiago de los Caballeros', 'Santo Domingo Oeste', 'Santo Domingo Este', 'Santo Domingo Norte', 'Santiago', 'San Pedro de Macorís', 'La Romana', 'San Cristóbal', 'San Francisco de Macorís'],
  'JM': ['Kingston', 'Spanish Town', 'Montego Bay', 'Portmore', 'Ocho Rios', 'Mandeville', 'May Pen', 'Old Harbour', 'Linstead', 'Half Way Tree'],
  'TT': ['Chaguanas', 'Mon Repos', 'San Fernando', 'Port of Spain', 'Rio Claro', 'Arima', 'Point Fortin', 'Princes Town', 'Scarborough', 'Marabella'],
  'BB': ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba', 'Holetown', 'Crane', 'Blackmans', 'Greenland', 'Hillcrest', 'Warrens'],
  'BS': ['Nassau', 'Lucaya', 'Freeport', 'West End', 'Cooper\'s Town', 'Marsh Harbour', 'High Rock', 'Andros Town', 'Clarence Town', 'Dunmore Town'],
  'BZ': ['Belize City', 'San Ignacio', 'Orange Walk', 'Belmopan', 'Dangriga', 'Corozal', 'San Pedro', 'Benque Viejo del Carmen', 'Punta Gorda', 'Valley of Peace'],
  'SV': ['San Salvador', 'Santa Ana', 'San Miguel', 'Mejicanos', 'Soyapango', 'Santa Tecla', 'Apopa', 'Delgado', 'Sonsonate', 'Ahuachapán'],
  'HN': ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba', 'El Progreso', 'Choluteca', 'Comayagua', 'Puerto Cortés', 'La Lima', 'Danlí'],
  'NI': ['Managua', 'León', 'Chinandega', 'Masaya', 'Estelí', 'Granada', 'Matagalpa', 'Jinotega', 'El Viejo', 'Nueva Guinea'],
  'CR': ['San José', 'Puerto Viejo', 'Liberia', 'Puntarenas', 'Limón', 'San Isidro', 'Curridabat', 'Turrialba', 'San Carlos', 'Alajuela'],
  'PA': ['Panamá', 'San Miguelito', 'Juan Díaz', 'David', 'Arraiján', 'Colón', 'Las Cumbres', 'La Chorrera', 'Pacora', 'Santiago'],
  'UY': ['Montevideo', 'Salto', 'Paysandú', 'Las Piedras', 'Rivera', 'Maldonado', 'Tacuarembó', 'Melo', 'Mercedes', 'Artigas'],
  'PY': ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá', 'Lambaré', 'Fernando de la Mora', 'Limpio', 'Ñemby', 'Encarnación'],
  'BO': ['Santa Cruz de la Sierra', 'El Alto', 'La Paz', 'Cochabamba', 'Oruro', 'Sucre', 'Potosí', 'Tarija', 'Sacaba', 'Montero'],
  'EC': ['Guayaquil', 'Quito', 'Cuenca', 'Santo Domingo', 'Machala', 'Durán', 'Manta', 'Portoviejo', 'Loja', 'Ambato'],
  'PE': ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Cusco', 'Chimbote', 'Huancayo', 'Pucallpa'],
  'CO': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Cúcuta', 'Bucaramanga', 'Pereira', 'Santa Marta', 'Ibagué'],
  'VE': ['Caracas', 'Maracaibo', 'Maracay', 'Valencia', 'Barcelona', 'Ciudad Guayana', 'Turmero', 'Maturín', 'Cumaná', 'Cabimas'],
  'GY': ['Georgetown', 'Linden', 'New Amsterdam', 'Bartica', 'Skeldon', 'Rosignol', 'Mahaica', 'Fort Wellington', 'Mahaicony', 'Anna Regina'],
  'SR': ['Paramaribo', 'Lelydorp', 'Brokopondo', 'Nieuw Nickerie', 'Moengo', 'Nieuw Amsterdam', 'Marienburg', 'Wageningen', 'Albina', 'Groningen'],
  'GF': ['Cayenne', 'Saint-Laurent-du-Maroni', 'Kourou', 'Sinnamary', 'Rémire-Montjoly', 'Matoury', 'Mana', 'Macouria', 'Montsinéry-Tonnegrande', 'Roura'],
  'CL': ['Santiago', 'Puente Alto', 'Antofagasta', 'Viña del Mar', 'Valparaíso', 'Talcahuano', 'San Bernardo', 'Temuco', 'Iquique', 'Concepción'],
  'AR': ['Buenos Aires', 'Córdoba', 'Rosario', 'La Plata', 'Mar del Plata', 'San Miguel de Tucumán', 'Salta', 'Santa Fe', 'San Juan', 'Resistencia'],
};

// Get all countries as an array of objects compatible with world-countries format
export const getCountriesList = () => {
  return Object.keys(COUNTRIES_AND_CITIES)
    .map(code => ({
      cca2: code,
      name: { common: code } // This will be replaced with actual country names
    }))
    .sort((a, b) => a.cca2.localeCompare(b.cca2));
};

// Get cities for a specific country
export const getCitiesForCountry = (countryCode: string): string[] => {
  return COUNTRIES_AND_CITIES[countryCode] || [];
};
